numero1=int(input('valor decimal: '))
# hexa=int(input('valor hexa: '))
# octal=int(input('valor oct: '))
print(f"numero em hexadecimal, {hex(numero1)}")
print(f"numero em octal,       {oct(numero1)}")
print(f"numero em octal,       {bin(numero1)}")