n1 = int(input('VALOR: '))
n2 = int(input('VALOR: '))
adicao = (n1 + n2)
subtracao = (n1 - n2)
multiplicacao = (n1 * n2)
divisao = (n1 / n2)
print('VALOR DA OPERACAO: ' , adicao)
print('VALOR DA OPERACAO: ' , subtracao)
print('VALOR DA OPERACAO: ' , divisao)
print('VALOR DA OPERACAO: ' , multiplicacao)